name: Build and deploy Node.js app to Azure Web App - FinFlow-RG-EA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: server  # your backend folder

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build (if any)
        run: npm run build --if-present

      - name: Run tests (optional)
        run: npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r server.zip .  # <- create zip inside `server/` folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server/server.zip  # <- inside workspace

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact  # folder to store artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5777804D4C6425E9CDA3DB261764623 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_941A4F24EECD4A4E8C40A5B56FFCB501 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AFA51D8FDD04434CB41EF92D987C9385 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FinFlow-RG-EA'
          slot-name: 'Production'
          package: ./artifact/server.zip  # <- path inside workspace
